language: ruby
sudo: false
cache: bundler
dist: trusty
rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - ruby-head
  - jruby-head
  - rbx-3
matrix:
  include:
    - rvm: 1.9
      before_install: &UPDATE_BUNDLER_BEFORE_INSTALL
        - gem update --system
        - gem install bundler
        - gem cleanup bundler
    - rvm: 2.3 # Check one ruby version against macos
      os: osx
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx-3
    - os: osx
  fast_finish: true
deploy:
  provider: rubygems
  api_key:
    secure: KcBpkFaes74KGMm8X/rRA8e13+t3PmkefsAvOAR+iF4g1GyuLSPkP92Fb9vFfsXBph+qmFh5rNa2lIRf/3RXW6COxY7CMMaARxUfJOKE0rmIwF0qfKI+RZDh6abg92iYngunMZVN8WVft6Lv9ZTOYCWxr1Zs1Ll/Rl4PfvHNd1g=
  gem: travis
  on:
    repo: travis-ci/travis.rb
    ruby: 2.0
    condition: "$(uname) = Linux"
