language: ruby
sudo: false
cache: bundler
os:
  - linux
  - osx
matrix:
  include:
  - rvm: 2.4
    os: linux
  - rvm: 2.4
    os: osx
    before_install: brew install openssl
  - rvm: 2.4
    os: osx
    before_install: brew install openssl@1.1
  fast_finish: true
  allow_failures:
    - os: osx
deploy:
  provider: rubygems
  api_key:
    secure: KcBpkFaes74KGMm8X/rRA8e13+t3PmkefsAvOAR+iF4g1GyuLSPkP92Fb9vFfsXBph+qmFh5rNa2lIRf/3RXW6COxY7CMMaARxUfJOKE0rmIwF0qfKI+RZDh6abg92iYngunMZVN8WVft6Lv9ZTOYCWxr1Zs1Ll/Rl4PfvHNd1g=
  gem: travis
  on:
    repo: travis-ci/travis.rb
    ruby: 2.0
    condition: "$(uname) = Linux"
